_wandb:
    value:
        cli_version: 0.25.0
        e:
            u3jdgjw0dax4glibet6lb6idd70ewj7u:
                codePath: scripts\backfill_wandb.py
                codePathLocal: scripts\backfill_wandb.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "510627483648"
                        used: "356946944000"
                email: tanishqsharma1.ts@gmail.com
                executable: C:\Users\tanis\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: da0fa317c727582f78cffaca806ab7a020c45ce9
                    remote: https://github.com/UtkarshMitta/adaptive-query-router-agent.git
                host: Tan_ishq
                memory:
                    total: "16535863296"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\tanis\Hackathon Mistral\router\adaptive-query-router-agent\scripts\backfill_wandb.py
                python: CPython 3.12.8
                root: C:\Users\tanis\Hackathon Mistral\router\adaptive-query-router-agent
                startedAt: "2026-03-01T10:12:16.516201Z"
                writerId: u3jdgjw0dax4glibet6lb6idd70ewj7u
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.8
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
type:
    value: recovery
